### PR TITLE
make it build as x86 on linux as well

### PR DESCRIPTION
**Pull request by LennyPenny**

### CODE REVIEW

**Comment by LennyPenny** [comment]
why did trin even change this D:

**Comment by alexrsagen** [comment]
Because "architecture" is an invalid option on linux. I don't care if you think i'm missing dependencies because i know i'm not, it really is just an invalid option on linux.

**Comment by meepen** [comment]
it is not invalid. i use it fine.

**Comment by alexrsagen** [comment]
```~/gm_stringtable$ premake5
Error: /home/trinityx/gm_stringtable/premake5.lua:8: invalid value 'x86'
```

It's invalid. My build server is the only build server on build.glua.io, so if it's invalid there, it's invalid.

**Comment by meepen** [comment]
it's not invalid.

**Comment by alexrsagen** [comment]
It says right it's invalid there you imbecile. I literally just updated premake5 to latest, and lib32stdc++6 is installed.

**Comment by meepen** [comment]
```
meep@meep-Lenovo-G510:~/git/aim-flex/aim-flex_csgo$ cat premake5.lua | grep architecture
        architecture "x86"
meep@meep-Lenovo-G510:~/git/aim-flex/aim-flex_csgo$ premake5 gmake
Building configurations...
Running action 'gmake'...
Generating proj/Makefile...
Generating proj/lua-flex.make...
Generating proj/lua53.make...
Done.
meep@meep-Lenovo-G510:~/git/aim-flex/aim-flex_csgo$ 
```

**Comment by alexrsagen** [comment]
Unless you're coming with a fix, i'm reverting this merge, and the other one as well.

**Comment by meepen** [comment]
No you aren't. It works fine.

**Comment by alexrsagen** [comment]
Yes, i am unless someone's coming with a fix. It doesn't work for me with a valid setup.

**Comment by LennyPenny** [comment]
If your build server is x64 then reverting it wont make sense since then modules are gonna be built as x64 and they are not gonna work on gmod. 
If your server is x32 then just make an env var, and make a commit that checks for that env var and either runs architecuture "x86" or not. 

It's shit but it's better than not having it build on developers machines or not having it build on the server.

**Comment by meepen** [comment]
Just update premake5.

**Comment by alexrsagen** [comment]
My build server is running 64-bit, but it should be able to build 32-bit stuff just fine, it's done that before. PREMAKE5 IS LATEST YOU RETARD MEEP.

**Comment by meepen** [comment]
I literally just updated premake5 to the latest, and tested it again. It works perfectly fine.

**Comment by LennyPenny** [comment]
Build a module and then run "file <filename>" on that binary file. It shoudl say smth like 

> [bin] file libgm_stringtable.so                                       master  ✭
> libgm_stringtable.so: ELF 32-bit LSB shared object, 

If it says smth like 64 then it wont work anyway

**Comment by alexrsagen** [comment]
Fucking hell, my premake was in the wrong location and overriding the latest one. Never fucking mind.

**Comment by sohpeach** [comment]
:lollipop:

**Comment by LennyPenny** [comment]
hahaha
rekt

**Comment by alexrsagen** [comment]
However, the build scripts are missing from this, so that needs to be added.

**Comment by meepen** [comment]
just do `premake5 gmake`

**Comment by handsomematt** [comment]
hehe u guys 😂😂😂😂😂😂👌👌👌👌👌👌👌

**Comment by PotcFdk** [comment]
@alexrsagen can't take the public shame.

**Comment by alexrsagen** [comment]
I am dishonor to famiry! Tried checking version with premake5 -v and --version to no avail, and so assumed the update i had done only a week ago had worked (putting the latest premake5 in /usr/bin).

However, i had a premake5 that was overriding it located in /usr/local/bin. Welp, i'm dumb.

**Comment by SwadicalRag** [comment]
i'm not sure what exactly happened, but you are forgiven

**Pull request merged**
